#!/bin/bash
# ALT DESKTOP ENV

####### Alt lightweight desktop (you need nm-applet also)
dnf install lxde-common lxde-icon-theme xscreensaver-base lxrandr network-manager-applet blueman -y

## XFCE
dnf install @xfce-desktop ffmpegthumbnailer -y

###### KDE Plasma
dnf install plasma-desktop dolphin kdeconnectd kscreen -y


# specify default session in /var/lib/AccountsService/users/$USER
sed -i 's/LXDE/gnome-session/g' /var/lib/AccountsService/users/$USER




# i3 Desktop
dnf install i3 i3status dmenu i3lock xbacklight feh conky -y


